packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  "@biomejs/biome": ^2.4.2
  "@vitejs/plugin-vue": ^6.0.4
  "@vue/test-utils": ^2.4.6
  jsdom: ^28.1.0
  tsup: ^8.5.0
  turbo: ^2.8.10
  typescript: ^5.0.0
  vite: ^7.3.1
  vite-plugin-dts: ^4.3.0
  vitest: ^4.0.18
  vue: ^3.5.0
