packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  "@biomejs/biome": ^2.0.0
  "@vitejs/plugin-vue": ^5.2.0
  "@vue/test-utils": ^2.4.6
  jsdom: ^25.0.1
  tsup: ^8.5.0
  turbo: ^2.3.0
  typescript: ^5.0.0
  vite: ^6.0.0
  vite-plugin-dts: ^4.3.0
  vitest: ^3.2.0
  vue: ^3.5.0
